esphome:
  name: "co2-sensor-${room_slug}"

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Co2 Sensor Fallback Hotspot"
    password: !secret ap_password

mqtt:
  broker: !secret mqtt_hostname

i2c:
  sda: GPIO19
  scl: GPIO20
  scan: true
  id: bus_a

sensor:
  - platform: scd4x
    temperature_offset: -5.6
    co2:
      name: "${room_title} CO2"
      state_topic: "esphome/${room_slug}/co2"
    temperature:
      name: "${room_title} Temperature"
      state_topic: "esphome/${room_slug}/temperature"
    humidity:
      name: "${room_title} Humidity"
      state_topic: "esphome/${room_slug}/humidity"

captive_portal:
