esphome:
  name: geekmagic
  friendly_name: Mini Display TV

esp8266:
  board: d1_mini

# Enable logging
logger:

web_server:
  port: 80

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mini-Display-Tv"
    password: "12345678"

mqtt:
  broker: !secret mqtt_hostname
  on_json_message:
    - topic: zigbee2mqtt/sensors/office/outdoors_temperature
      then:
        - lambda: |-
            id(outdoor_temp).publish_state(x["temperature"]);
    - topic: zigbee2mqtt/sensors/office/closet_temperature
      then:
        - lambda: |-
            id(indoor_humidity).publish_state(x["humidity"]);

captive_portal:

spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  interface: hardware
  id: spihwd

# status_led:
#   pin: GPIO2

output:
  - platform: esp8266_pwm
    pin: GPIO05
    frequency: 200 Hz
    inverted: true
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Backlight"
    id: backlight
    restore_mode: RESTORE_AND_ON

font:
  - file: "gfonts://Bebas+Neue"
    id: font_time
    size: 137

  - file: "gfonts://Exo+2"
    id: font_info
    size: 22

display:
  - platform: mipi_spi
    model: st7789v
    spi_id: spihwd
    dimensions:
      height: 240
      width: 240
      offset_height: 0
      offset_width: 0
    invert_colors: true
    dc_pin: GPIO00
    reset_pin: GPIO02
    #backlight_pin: GPIO25
    color_depth: 8
    update_interval: 1s
    id: disp
    spi_mode: mode3
    lambda: |-
      it.fill(Color::BLACK);

      Color red = Color(255, 80, 80);
      Color white = Color(255, 255, 255);
      int bx, by, bw, bh;

      auto time = id(current_time).now();
      if (time.is_valid()) {
        it.strftime(5, 10, id(font_time), red, "%H", time);
        it.strftime(235, 75, id(font_time), white, TextAlign::TOP_RIGHT, "%M", time);

        // Date: dayname(red) day(white)/(red)month(white), right-aligned.
        int pos = 235;

        char month_str[4];
        sprintf(month_str, "%02d", time.month);
        it.get_text_bounds(0, 0, month_str, id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
        pos -= bw;
        it.print(pos, 0, id(font_info), white, month_str);

        it.get_text_bounds(0, 0, "/", id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
        pos -= bw;
        it.print(pos, 0, id(font_info), white, "/");

        char day_str[4];
        sprintf(day_str, "%02d", time.day_of_month);
        it.get_text_bounds(0, 0, day_str, id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
        pos -= bw;
        it.print(pos, 0, id(font_info), white, day_str);

        it.get_text_bounds(0, 0, " ", id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
        pos -= bw;

        const char* daynames[] = {"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"};
        const char* dayname = daynames[time.day_of_week - 1];
        it.print(pos, 0, id(font_info), white, TextAlign::TOP_RIGHT, dayname);
      } else {
        it.printf(5, 10, id(font_time), red, "NA");
        it.printf(235, 75, id(font_time), white, TextAlign::TOP_RIGHT, "NA");
      }

      // Bottom: outdoor temp on left, indoor humidity and CO2 on right.
      float temp = isnan(id(outdoor_temp).state) ? 0 : id(outdoor_temp).state;
      float humidity = isnan(id(indoor_humidity).state) ? 0 : id(indoor_humidity).state;
      float co2 = isnan(id(bedroom_co2).state) ? 0 : id(bedroom_co2).state;

      // Temperature: number(white) + °C(red).
      char temp_num[8];
      sprintf(temp_num, "%.1f", temp);
      it.print(5, 214, id(font_info), white, temp_num);
      it.get_text_bounds(0, 0, temp_num, id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
      it.print(5 + bw, 214, id(font_info), red, "°C");

      // Right side: humidity(white) %(red) space co2(white) ppt(red).
      int rpos = 235;

      it.get_text_bounds(0, 0, "ppt", id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
      rpos -= bw;
      it.print(rpos, 214, id(font_info), red, "ppt");

      char co2_str[8];
      sprintf(co2_str, "%.1f", co2 / 1000);
      it.get_text_bounds(0, 0, co2_str, id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
      rpos -= bw;
      it.print(rpos, 214, id(font_info), white, co2_str);

      it.get_text_bounds(0, 0, " ", id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
      rpos -= bw;

      it.get_text_bounds(0, 0, "%", id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
      rpos -= bw;
      it.print(rpos, 214, id(font_info), red, "%");

      char hum_str[8];
      sprintf(hum_str, "%.0f", humidity);
      it.get_text_bounds(0, 0, hum_str, id(font_info), TextAlign::TOP_LEFT, &bx, &by, &bw, &bh);
      rpos -= bw;
      it.print(rpos, 214, id(font_info), white, hum_str);

sensor:
  - platform: mqtt_subscribe
    name: "Bedroom CO2"
    id: bedroom_co2
    topic: zigbee2mqtt/sensors/bedroom/co2

  - platform: template
    name: "Outdoor Temperature"
    id: outdoor_temp
    unit_of_measurement: "°C"

  - platform: template
    name: "Indoor Humidity"
    id: indoor_humidity
    unit_of_measurement: "%"

time:
  - platform: sntp
    id: current_time
    timezone: Europe/Athens
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

interval:
  - interval: 1min
    then:
      - lambda: |-
          auto time = id(current_time).now();
          if (!time.is_valid()) return;

          // Calculate minutes since midnight.
          int minutes = time.hour * 60 + time.minute;

          // Peak brightness (60%) at 14:00 (840 minutes), minimum (15%) at 00:00.
          float brightness;
          if (minutes <= 840) {
            brightness = 0.15 + 0.45 * minutes / 840.0;
          } else {
            brightness = 0.60 - 0.45 * (minutes - 840) / 600.0;
          }

          auto call = id(backlight).turn_on();
          call.set_brightness(brightness);
          call.perform();
